version: '3.4'

services:
  
  postgres:
    container_name: ttt-db
    image: postgres:12.8
    environment:
      POSTGRES_DB: "ttt_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - ./db_build:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
     - my_network
  tictactoe:
    container_name: web-api
    image: ${DOCKER_REGISTRY-}tictactoe
    links:
      - postgres
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: TicTacToe/Dockerfile
    networks:
     - my_network
networks:
  my_network:
    driver: bridge
