version: '3.4'

services:
  tictactoe:
    container_name: web-api
    image: ${DOCKER_REGISTRY-}tictactoe
    build:
      context: .
      dockerfile: TicTacToe/Dockerfile
  postgres:
    container_name: ttt-db
    image: postgres:12.8
    environment:
      POSTGRES_DB: "ttt_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - ./db_build:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
